<a href="https://colab.research.google.com/github/loisstetson/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [31]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [32]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [33]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [34]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [35]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 500

application_types_to_replace = list(application_type_counts[application_type_counts < cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [39]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [38]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filtered_counts = classification_counts[classification_counts > 1]
print(filtered_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [40]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 500
classifications_to_replace = list(classification_counts[classification_counts < cutoff].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [41]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummies = pd.get_dummies(application_df)
df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [47]:
# Split our preprocessed data into our features and target arrays
target = 'IS_SUCCESSFUL'
features = df_dummies.drop(target, axis=1)

X = features
y = df_dummies[target]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_train_scaled = scaler.fit_transform(X_train)

# Scale the data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
n_features = X_train_scaled.shape[1]
n_nodes_layer1 = 80
n_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=n_nodes_layer1, activation='relu', input_dim=n_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=n_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3600

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6061 (23.68 KB)
Trainable params: 6061 (23.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [52]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [54]:
# Train the model
num_epochs = 100
batch_size = 32

history = nn.fit(X_train_scaled, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(X_test_scaled, y_test))

Epoch 1/100
858/858 [==============================] - 6s 5ms/step - loss: 0.5674 - accuracy: 0.7215 - val_loss: 0.5668 - val_accuracy: 0.7184
Epoch 2/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5545 - accuracy: 0.7295 - val_loss: 0.5606 - val_accuracy: 0.7197
Epoch 3/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7305 - val_loss: 0.5571 - val_accuracy: 0.7261
Epoch 4/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7307 - val_loss: 0.5612 - val_accuracy: 0.7251
Epoch 5/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7322 - val_loss: 0.5585 - val_accuracy: 0.7261
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7326 - val_loss: 0.5580 - val_accuracy: 0.7249
Epoch 7/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5460 - accuracy: 0.7327 - val_loss: 0.5540 - val_accuracy: 0.7227
Epoch 8/100
858/858 [==============================] - 5s 6ms/step - loss: 0.5454 - accuracy: 0.7324 - val_loss: 0.5563 - val_accuracy: 0.7245
Epoch 9/100
858/858 [==============================] - 5s 6ms/step - loss: 0.5453 - accuracy: 0.7348 - val_loss: 0.5571 - val_accuracy: 0.7204
Epoch 10/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5443 - accuracy: 0.7344 - val_loss: 0.5534 - val_accuracy: 0.7284
Epoch 11/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5444 - accuracy: 0.7339 - val_loss: 0.5553 - val_accuracy: 0.7281
Epoch 12/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7349 - val_loss: 0.5561 - val_accuracy: 0.7294
Epoch 13/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7345 - val_loss: 0.5538 - val_accuracy: 0.7289
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7350 - val_loss: 0.5566 - val_accuracy: 0.7273
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7354 - val_loss: 0.5577 - val_accuracy: 0.7224
Epoch 16/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5421 - accuracy: 0.7361 - val_loss: 0.5530 - val_accuracy: 0.7283
Epoch 17/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5422 - accuracy: 0.7359 - val_loss: 0.5549 - val_accuracy: 0.7267
Epoch 18/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7353 - val_loss: 0.5542 - val_accuracy: 0.7243
Epoch 19/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7360 - val_loss: 0.5548 - val_accuracy: 0.7284
Epoch 20/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7356 - val_loss: 0.5545 - val_accuracy: 0.7280
Epoch 21/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7367 - val_loss: 0.5552 - val_accuracy: 0.7286
Epoch 22/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7361 - val_loss: 0.5561 - val_accuracy: 0.7248
Epoch 23/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5411 - accuracy: 0.7355 - val_loss: 0.5550 - val_accuracy: 0.7277
Epoch 24/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5404 - accuracy: 0.7377 - val_loss: 0.5555 - val_accuracy: 0.7235
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7353 - val_loss: 0.5545 - val_accuracy: 0.7254
Epoch 26/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7365 - val_loss: 0.5553 - val_accuracy: 0.7284
Epoch 27/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7371 - val_loss: 0.5554 - val_accuracy: 0.7271
Epoch 28/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5395 - accuracy: 0.7367 - val_loss: 0.5552 - val_accuracy: 0.7262
Epoch 29/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5393 - accuracy: 0.7376 - val_loss: 0.5578 - val_accuracy: 0.7257
Epoch 30/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7374 - val_loss: 0.5563 - val_accuracy: 0.7257
Epoch 31/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7373 - val_loss: 0.5560 - val_accuracy: 0.7265
Epoch 32/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7364 - val_loss: 0.5552 - val_accuracy: 0.7284
Epoch 33/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7369 - val_loss: 0.5548 - val_accuracy: 0.7271
Epoch 34/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5385 - accuracy: 0.7370 - val_loss: 0.5552 - val_accuracy: 0.7267
Epoch 35/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7385 - val_loss: 0.5538 - val_accuracy: 0.7277
Epoch 36/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7377 - val_loss: 0.5566 - val_accuracy: 0.7267
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7374 - val_loss: 0.5569 - val_accuracy: 0.7239
Epoch 38/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7383 - val_loss: 0.5576 - val_accuracy: 0.7268
Epoch 39/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7376 - val_loss: 0.5558 - val_accuracy: 0.7278
Epoch 40/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5380 - accuracy: 0.7383 - val_loss: 0.5559 - val_accuracy: 0.7286
Epoch 41/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7388 - val_loss: 0.5560 - val_accuracy: 0.7259
Epoch 42/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7391 - val_loss: 0.5575 - val_accuracy: 0.7294
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7377 - val_loss: 0.5582 - val_accuracy: 0.7261
Epoch 44/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7385 - val_loss: 0.5558 - val_accuracy: 0.7287
Epoch 45/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7382 - val_loss: 0.5573 - val_accuracy: 0.7277
Epoch 46/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5369 - accuracy: 0.7387 - val_loss: 0.5583 - val_accuracy: 0.7290
Epoch 47/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5372 - accuracy: 0.7384 - val_loss: 0.5582 - val_accuracy: 0.7268
Epoch 48/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5370 - accuracy: 0.7385 - val_loss: 0.5580 - val_accuracy: 0.7258
Epoch 49/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5366 - accuracy: 0.7382 - val_loss: 0.5575 - val_accuracy: 0.7267
Epoch 50/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7382 - val_loss: 0.5600 - val_accuracy: 0.7249
Epoch 51/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7388 - val_loss: 0.5589 - val_accuracy: 0.7274
Epoch 52/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7385 - val_loss: 0.5569 - val_accuracy: 0.7258
Epoch 53/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5362 - accuracy: 0.7392 - val_loss: 0.5583 - val_accuracy: 0.7259
Epoch 54/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7393 - val_loss: 0.5590 - val_accuracy: 0.7286
Epoch 55/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7389 - val_loss: 0.5572 - val_accuracy: 0.7292
Epoch 56/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.7397 - val_loss: 0.5589 - val_accuracy: 0.7258
Epoch 57/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7391 - val_loss: 0.5576 - val_accuracy: 0.7290
Epoch 58/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7397 - val_loss: 0.5595 - val_accuracy: 0.7287
Epoch 59/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7387 - val_loss: 0.5556 - val_accuracy: 0.7277
Epoch 60/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7399 - val_loss: 0.5605 - val_accuracy: 0.7249
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7401 - val_loss: 0.5591 - val_accuracy: 0.7276
Epoch 62/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7389 - val_loss: 0.5560 - val_accuracy: 0.7286
Epoch 63/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7389 - val_loss: 0.5583 - val_accuracy: 0.7257
Epoch 64/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7396 - val_loss: 0.5623 - val_accuracy: 0.7238
Epoch 65/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7399 - val_loss: 0.5597 - val_accuracy: 0.7302
Epoch 66/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7397 - val_loss: 0.5578 - val_accuracy: 0.7293
Epoch 67/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7396 - val_loss: 0.5578 - val_accuracy: 0.7297
Epoch 68/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7383 - val_loss: 0.5611 - val_accuracy: 0.7293
Epoch 69/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7396 - val_loss: 0.5618 - val_accuracy: 0.7248
Epoch 70/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7384 - val_loss: 0.5590 - val_accuracy: 0.7270
Epoch 71/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7389 - val_loss: 0.5624 - val_accuracy: 0.7297
Epoch 72/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7391 - val_loss: 0.5603 - val_accuracy: 0.7265
Epoch 73/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7394 - val_loss: 0.5587 - val_accuracy: 0.7284
Epoch 74/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7403 - val_loss: 0.5606 - val_accuracy: 0.7255
Epoch 75/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7401 - val_loss: 0.5604 - val_accuracy: 0.7255
Epoch 76/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5346 - accuracy: 0.7398 - val_loss: 0.5618 - val_accuracy: 0.7267
Epoch 77/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7394 - val_loss: 0.5594 - val_accuracy: 0.7261
Epoch 78/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7398 - val_loss: 0.5608 - val_accuracy: 0.7242
Epoch 79/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7392 - val_loss: 0.5613 - val_accuracy: 0.7281
Epoch 80/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7399 - val_loss: 0.5641 - val_accuracy: 0.7238
Epoch 81/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7404 - val_loss: 0.5598 - val_accuracy: 0.7286
Epoch 82/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7399 - val_loss: 0.5617 - val_accuracy: 0.7296
Epoch 83/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7397 - val_loss: 0.5615 - val_accuracy: 0.7278
Epoch 84/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7394 - val_loss: 0.5626 - val_accuracy: 0.7261
Epoch 85/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7399 - val_loss: 0.5628 - val_accuracy: 0.7292
Epoch 86/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7391 - val_loss: 0.5611 - val_accuracy: 0.7281
Epoch 87/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5342 - accuracy: 0.7403 - val_loss: 0.5594 - val_accuracy: 0.7290
Epoch 88/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7401 - val_loss: 0.5619 - val_accuracy: 0.7280
Epoch 89/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7393 - val_loss: 0.5616 - val_accuracy: 0.7276
Epoch 90/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7397 - val_loss: 0.5632 - val_accuracy: 0.7273
Epoch 91/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7394 - val_loss: 0.5644 - val_accuracy: 0.7300
Epoch 92/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7407 - val_loss: 0.5632 - val_accuracy: 0.7281
Epoch 93/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5335 - accuracy: 0.7403 - val_loss: 0.5638 - val_accuracy: 0.7257
Epoch 94/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5339 - accuracy: 0.7404 - val_loss: 0.5619 - val_accuracy: 0.7278
Epoch 95/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7399 - val_loss: 0.5606 - val_accuracy: 0.7268
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7400 - val_loss: 0.5619 - val_accuracy: 0.7265
Epoch 97/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7404 - val_loss: 0.5619 - val_accuracy: 0.7254
Epoch 98/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7397 - val_loss: 0.5650 - val_accuracy: 0.7267
Epoch 99/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5350 - accuracy: 0.7401 - val_loss: 0.5652 - val_accuracy: 0.7242
Epoch 100/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7392 - val_loss: 0.5670 - val_accuracy: 0.7258

In [55]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5670 - accuracy: 0.7258 - 371ms/epoch - 2ms/step
Loss: 0.5669689774513245, Accuracy: 0.7258017659187317

In [57]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.keras")